baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Practica de Hugo'
theme = "stack"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
identifier = "home"
icon = "/images/home.svg"  # Ruta relativa a la carpeta 'static/images'
newTab = true

[[menu.main]]
name = "Contenidos"
url = "/page/contenidos/"
weight = 2
identifier = "contenidos"
icon = "/images/user.svg"  # Ruta relativa a la carpeta 'static/images'
newTab = true

[[menu.main]]
name = "Carrusel"
url = "/page/imagenes/"
weight = 3
identifier = "carrusel"
icon = "/images/link.svg"  # Ruta relativa a la carpeta 'static/images'
newTab = true

[[menu.main]]
name = "Markdown"
url = "/page/markdown/"
weight = 4
identifier = "markdown"
icon = "/images/hash.svg"  # Ruta relativa a la carpeta 'static/images'
newTab = true

[[menu.main]]
name = "TV"
url = "/page/tv/"
weight = 5
identifier = "tv"
icon = "/images/tag.svg"  # Ruta relativa a la carpeta 'static/images'
newTab = true