#baseURL = 'https://ManuelAznar1.github.io/practica_hugo/'
languageCode = 'en-us'
title = 'Practica de Hugo'
theme = "stack"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
identifier = "home"
icon = "/icons/home.svg"  # Ruta a la carpeta 'static/icons'
newTab = true

[[menu.main]]
name = "Contenidos"
url = "/page/contenidos/"
weight = 2
identifier = "contenidos"
icon = "/icons/user.svg"  # Ruta a la carpeta 'static/icons'
newTab = true

[[menu.main]]
name = "Carrusel"
url = "/page/imagenes/"
weight = 3
identifier = "carrusel"
icon = "/icons/link.svg"  # Ruta a la carpeta 'static/icons'
newTab = true

[[menu.main]]
name = "Markdown"
url = "/page/markdown/"
weight = 4
identifier = "markdown"
icon = "/icons/hash.svg"  # Ruta a la carpeta 'static/icons'
newTab = true

[[menu.main]]
name = "TV"
url = "/page/tv/"
weight = 5
identifier = "tv"
icon = "/icons/tag.svg"  # Ruta a la carpeta 'static/icons'
newTab = true
